"""empty message

Revision ID: 13f89f258ad9
Revises: dc9050666523
Create Date: 2016-05-04 17:35:56.447486

"""

# revision identifiers, used by Alembic.
revision = '13f89f258ad9'
down_revision = 'dc9050666523'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
