"""empty message

Revision ID: ed2064e6fcd4
Revises: 547a95c2fc9a
Create Date: 2016-05-01 22:45:55.940634

"""

# revision identifiers, used by Alembic.
revision = 'ed2064e6fcd4'
down_revision = '547a95c2fc9a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
